import React from "react";
export declare enum ButtonType {
    Standard = 0,
    White = 1,
    Gray = 2,
    Clear = 3
}
declare type ButtonProps = {
    children: React.ReactNode;
    disabled?: boolean;
    buttonType?: ButtonType;
    className?: string;
};
declare const Button: import("styled-components").StyledComponent<"button", import("styled-components").DefaultTheme, {
    form?: string | undefined;
    slot?: string | undefined;
    style?: React.CSSProperties | undefined;
    title?: string | undefined;
    type: "button" | "submit" | "reset";
    name?: string | undefined;
    key?: string | number | null | undefined;
    css?: string | import("styled-components").CSSObject | import("styled-components").FlattenInterpolation<import("styled-components").ThemeProps<import("styled-components").DefaultTheme>> | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    className?: string | undefined;
    contentEditable?: boolean | "true" | "false" | "inherit" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: boolean | "true" | "false" | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    placeholder?: string | undefined;
    spellCheck?: boolean | "true" | "false" | undefined;
    tabIndex?: number | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: "article" | "button" | "dialog" | "figure" | "form" | "img" | "link" | "main" | "menu" | "menuitem" | "option" | "table" | "switch" | "alert" | "alertdialog" | "application" | "banner" | "cell" | "checkbox" | "columnheader" | "combobox" | "complementary" | "contentinfo" | "definition" | "directory" | "document" | "feed" | "grid" | "gridcell" | "group" | "heading" | "list" | "listbox" | "listitem" | "log" | "marquee" | "math" | "menubar" | "menuitemcheckbox" | "menuitemradio" | "navigation" | "none" | "note" | "presentation" | "progressbar" | "radio" | "radiogroup" | "region" | "row" | "rowgroup" | "rowheader" | "scrollbar" | "search" | "searchbox" | "separator" | "slider" | "spinbutton" | "status" | "tab" | "tablist" | "tabpanel" | "term" | "textbox" | "timer" | "toolbar" | "tooltip" | "tree" | "treegrid" | "treeitem" | (string & {}) | undefined;
    about?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    resource?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "text" | "none" | "search" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    'aria-activedescendant'?: string | undefined;
    'aria-atomic'?: boolean | "true" | "false" | undefined;
    'aria-autocomplete'?: "list" | "none" | "inline" | "both" | undefined;
    'aria-busy'?: boolean | "true" | "false" | undefined;
    'aria-checked'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-colcount'?: number | undefined;
    'aria-colindex'?: number | undefined;
    'aria-colspan'?: number | undefined;
    'aria-controls'?: string | undefined;
    'aria-current'?: boolean | "time" | "true" | "false" | "date" | "step" | "page" | "location" | undefined;
    'aria-describedby'?: string | undefined;
    'aria-details'?: string | undefined;
    "aria-disabled": boolean | "true" | "false" | undefined;
    'aria-dropeffect'?: "copy" | "link" | "none" | "execute" | "move" | "popup" | undefined;
    'aria-errormessage'?: string | undefined;
    'aria-expanded'?: boolean | "true" | "false" | undefined;
    'aria-flowto'?: string | undefined;
    'aria-grabbed'?: boolean | "true" | "false" | undefined;
    'aria-haspopup'?: boolean | "dialog" | "menu" | "true" | "false" | "grid" | "listbox" | "tree" | undefined;
    'aria-hidden'?: boolean | "true" | "false" | undefined;
    'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
    'aria-keyshortcuts'?: string | undefined;
    'aria-label'?: string | undefined;
    'aria-labelledby'?: string | undefined;
    'aria-level'?: number | undefined;
    'aria-live'?: "off" | "assertive" | "polite" | undefined;
    'aria-modal'?: boolean | "true" | "false" | undefined;
    'aria-multiline'?: boolean | "true" | "false" | undefined;
    'aria-multiselectable'?: boolean | "true" | "false" | undefined;
    'aria-orientation'?: "horizontal" | "vertical" | undefined;
    'aria-owns'?: string | undefined;
    'aria-placeholder'?: string | undefined;
    'aria-posinset'?: number | undefined;
    'aria-pressed'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-readonly'?: boolean | "true" | "false" | undefined;
    'aria-relevant'?: "text" | "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    'aria-required'?: boolean | "true" | "false" | undefined;
    'aria-roledescription'?: string | undefined;
    'aria-rowcount'?: number | undefined;
    'aria-rowindex'?: number | undefined;
    'aria-rowspan'?: number | undefined;
    'aria-selected'?: boolean | "true" | "false" | undefined;
    'aria-setsize'?: number | undefined;
    'aria-sort'?: "none" | "ascending" | "descending" | "other" | undefined;
    'aria-valuemax'?: number | undefined;
    'aria-valuemin'?: number | undefined;
    'aria-valuenow'?: number | undefined;
    'aria-valuetext'?: string | undefined;
    children?: React.ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string;
    } | undefined;
    onCopy?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onCopyCapture?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onCut?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onCutCapture?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onPaste?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onPasteCapture?: ((event: React.ClipboardEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionEnd?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionEndCapture?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionStart?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionStartCapture?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionUpdate?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onCompositionUpdateCapture?: ((event: React.CompositionEvent<HTMLButtonElement>) => void) | undefined;
    onFocus?: ((event: React.FocusEvent<HTMLButtonElement, Element>) => void) | undefined;
    onFocusCapture?: ((event: React.FocusEvent<HTMLButtonElement, Element>) => void) | undefined;
    onBlur?: ((event: React.FocusEvent<HTMLButtonElement, Element>) => void) | undefined;
    onBlurCapture?: ((event: React.FocusEvent<HTMLButtonElement, Element>) => void) | undefined;
    onChange?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onChangeCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onBeforeInput?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onBeforeInputCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onInput?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onInputCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onReset?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onResetCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onSubmit?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onSubmitCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onInvalid?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onInvalidCapture?: ((event: React.FormEvent<HTMLButtonElement>) => void) | undefined;
    onLoad?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onError?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onErrorCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onKeyDown?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onKeyDownCapture?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onKeyPress?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onKeyPressCapture?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onKeyUp?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onKeyUpCapture?: ((event: React.KeyboardEvent<HTMLButtonElement>) => void) | undefined;
    onAbort?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onAbortCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onCanPlay?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onCanPlayCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onCanPlayThrough?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onCanPlayThroughCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onDurationChange?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onDurationChangeCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEmptied?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEmptiedCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEncrypted?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEncryptedCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEnded?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onEndedCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadedData?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadedDataCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadedMetadata?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadedMetadataCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadStart?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onLoadStartCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPause?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPauseCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPlay?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPlayCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPlaying?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onPlayingCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onProgress?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onProgressCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onRateChange?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onRateChangeCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSeeked?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSeekedCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSeeking?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSeekingCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onStalled?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onStalledCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSuspend?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSuspendCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onTimeUpdate?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onTimeUpdateCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onVolumeChange?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onVolumeChangeCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onWaiting?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onWaitingCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onAuxClick?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onAuxClickCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onClick?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onClickCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onContextMenu?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onContextMenuCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onDoubleClick?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onDoubleClickCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onDrag?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragEnd?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragEndCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragEnter?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragEnterCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragExit?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragExitCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragLeave?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragLeaveCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragOver?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragOverCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragStart?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDragStartCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDrop?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onDropCapture?: ((event: React.DragEvent<HTMLButtonElement>) => void) | undefined;
    onMouseDown?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseDownCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseEnter?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseLeave?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseMove?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseMoveCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseOut?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseOutCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseOver?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseOverCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseUp?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onMouseUpCapture?: ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void) | undefined;
    onSelect?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onSelectCapture?: ((event: React.SyntheticEvent<HTMLButtonElement, Event>) => void) | undefined;
    onTouchCancel?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchCancelCapture?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchEnd?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchEndCapture?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchMove?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchMoveCapture?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchStart?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onTouchStartCapture?: ((event: React.TouchEvent<HTMLButtonElement>) => void) | undefined;
    onPointerDown?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerDownCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerMove?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerMoveCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerUp?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerUpCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerCancel?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerCancelCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerEnter?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerEnterCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerLeave?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerLeaveCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerOver?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerOverCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerOut?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onPointerOutCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onGotPointerCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onGotPointerCaptureCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onLostPointerCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onLostPointerCaptureCapture?: ((event: React.PointerEvent<HTMLButtonElement>) => void) | undefined;
    onScroll?: ((event: React.UIEvent<HTMLButtonElement, UIEvent>) => void) | undefined;
    onScrollCapture?: ((event: React.UIEvent<HTMLButtonElement, UIEvent>) => void) | undefined;
    onWheel?: ((event: React.WheelEvent<HTMLButtonElement>) => void) | undefined;
    onWheelCapture?: ((event: React.WheelEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationStart?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationStartCapture?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationEnd?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationEndCapture?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationIteration?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onAnimationIterationCapture?: ((event: React.AnimationEvent<HTMLButtonElement>) => void) | undefined;
    onTransitionEnd?: ((event: React.TransitionEvent<HTMLButtonElement>) => void) | undefined;
    onTransitionEndCapture?: ((event: React.TransitionEvent<HTMLButtonElement>) => void) | undefined;
    autoFocus?: boolean | undefined;
    formAction?: string | undefined;
    formEncType?: string | undefined;
    formMethod?: string | undefined;
    formNoValidate?: boolean | undefined;
    formTarget?: string | undefined;
    value?: string | number | readonly string[] | undefined;
    ref?: ((instance: HTMLButtonElement | null) => void) | React.RefObject<HTMLButtonElement> | null | undefined;
    theme: import("styled-components").DefaultTheme;
} & ButtonProps, "form" | "slot" | "style" | "title" | "theme" | "ref" | "type" | "name" | "key" | "css" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "className" | "contentEditable" | "contextMenu" | "dir" | "draggable" | "hidden" | "id" | "lang" | "placeholder" | "spellCheck" | "tabIndex" | "translate" | "radioGroup" | "role" | "about" | "datatype" | "inlist" | "prefix" | "property" | "resource" | "typeof" | "vocab" | "autoCapitalize" | "autoCorrect" | "autoSave" | "color" | "itemProp" | "itemScope" | "itemType" | "itemID" | "itemRef" | "results" | "security" | "unselectable" | "inputMode" | "is" | "aria-activedescendant" | "aria-atomic" | "aria-autocomplete" | "aria-busy" | "aria-checked" | "aria-colcount" | "aria-colindex" | "aria-colspan" | "aria-controls" | "aria-current" | "aria-describedby" | "aria-details" | "aria-disabled" | "aria-dropeffect" | "aria-errormessage" | "aria-expanded" | "aria-flowto" | "aria-grabbed" | "aria-haspopup" | "aria-hidden" | "aria-invalid" | "aria-keyshortcuts" | "aria-label" | "aria-labelledby" | "aria-level" | "aria-live" | "aria-modal" | "aria-multiline" | "aria-multiselectable" | "aria-orientation" | "aria-owns" | "aria-placeholder" | "aria-posinset" | "aria-pressed" | "aria-readonly" | "aria-relevant" | "aria-required" | "aria-roledescription" | "aria-rowcount" | "aria-rowindex" | "aria-rowspan" | "aria-selected" | "aria-setsize" | "aria-sort" | "aria-valuemax" | "aria-valuemin" | "aria-valuenow" | "aria-valuetext" | "children" | "dangerouslySetInnerHTML" | "onCopy" | "onCopyCapture" | "onCut" | "onCutCapture" | "onPaste" | "onPasteCapture" | "onCompositionEnd" | "onCompositionEndCapture" | "onCompositionStart" | "onCompositionStartCapture" | "onCompositionUpdate" | "onCompositionUpdateCapture" | "onFocus" | "onFocusCapture" | "onBlur" | "onBlurCapture" | "onChange" | "onChangeCapture" | "onBeforeInput" | "onBeforeInputCapture" | "onInput" | "onInputCapture" | "onReset" | "onResetCapture" | "onSubmit" | "onSubmitCapture" | "onInvalid" | "onInvalidCapture" | "onLoad" | "onLoadCapture" | "onError" | "onErrorCapture" | "onKeyDown" | "onKeyDownCapture" | "onKeyPress" | "onKeyPressCapture" | "onKeyUp" | "onKeyUpCapture" | "onAbort" | "onAbortCapture" | "onCanPlay" | "onCanPlayCapture" | "onCanPlayThrough" | "onCanPlayThroughCapture" | "onDurationChange" | "onDurationChangeCapture" | "onEmptied" | "onEmptiedCapture" | "onEncrypted" | "onEncryptedCapture" | "onEnded" | "onEndedCapture" | "onLoadedData" | "onLoadedDataCapture" | "onLoadedMetadata" | "onLoadedMetadataCapture" | "onLoadStart" | "onLoadStartCapture" | "onPause" | "onPauseCapture" | "onPlay" | "onPlayCapture" | "onPlaying" | "onPlayingCapture" | "onProgress" | "onProgressCapture" | "onRateChange" | "onRateChangeCapture" | "onSeeked" | "onSeekedCapture" | "onSeeking" | "onSeekingCapture" | "onStalled" | "onStalledCapture" | "onSuspend" | "onSuspendCapture" | "onTimeUpdate" | "onTimeUpdateCapture" | "onVolumeChange" | "onVolumeChangeCapture" | "onWaiting" | "onWaitingCapture" | "onAuxClick" | "onAuxClickCapture" | "onClick" | "onClickCapture" | "onContextMenu" | "onContextMenuCapture" | "onDoubleClick" | "onDoubleClickCapture" | "onDrag" | "onDragCapture" | "onDragEnd" | "onDragEndCapture" | "onDragEnter" | "onDragEnterCapture" | "onDragExit" | "onDragExitCapture" | "onDragLeave" | "onDragLeaveCapture" | "onDragOver" | "onDragOverCapture" | "onDragStart" | "onDragStartCapture" | "onDrop" | "onDropCapture" | "onMouseDown" | "onMouseDownCapture" | "onMouseEnter" | "onMouseLeave" | "onMouseMove" | "onMouseMoveCapture" | "onMouseOut" | "onMouseOutCapture" | "onMouseOver" | "onMouseOverCapture" | "onMouseUp" | "onMouseUpCapture" | "onSelect" | "onSelectCapture" | "onTouchCancel" | "onTouchCancelCapture" | "onTouchEnd" | "onTouchEndCapture" | "onTouchMove" | "onTouchMoveCapture" | "onTouchStart" | "onTouchStartCapture" | "onPointerDown" | "onPointerDownCapture" | "onPointerMove" | "onPointerMoveCapture" | "onPointerUp" | "onPointerUpCapture" | "onPointerCancel" | "onPointerCancelCapture" | "onPointerEnter" | "onPointerEnterCapture" | "onPointerLeave" | "onPointerLeaveCapture" | "onPointerOver" | "onPointerOverCapture" | "onPointerOut" | "onPointerOutCapture" | "onGotPointerCapture" | "onGotPointerCaptureCapture" | "onLostPointerCapture" | "onLostPointerCaptureCapture" | "onScroll" | "onScrollCapture" | "onWheel" | "onWheelCapture" | "onAnimationStart" | "onAnimationStartCapture" | "onAnimationEnd" | "onAnimationEndCapture" | "onAnimationIteration" | "onAnimationIterationCapture" | "onTransitionEnd" | "onTransitionEndCapture" | "autoFocus" | "formAction" | "formEncType" | "formMethod" | "formNoValidate" | "formTarget" | "value">;
export default Button;
